apiVersion: v1
kind: ConfigMap
metadata:
  name: "challenge-misc-a-true-connection"
  labels:
    challenges.ctfpilot.com/type: "tcp"
    challenges.ctfpilot.com/name: "a-true-connection"
    challenges.ctfpilot.com/category: "misc"
    challenges.ctfpilot.com/version: "5"
    challenges.ctfpilot.com/configmap: "challenge-config"
    challenges.ctfpilot.com/enabled: "true"
    ctfpilot.com/component: "challenge-config"
data:
  name: "a-true-connection"
  path: "challenges/misc/a-true-connection"
  repository: "ctfpilot/challenges-example"
  generated_at: "2026-01-07 13:00:45"
  challenge: |
    {
      "$schema": "https://raw.githubusercontent.com/ctfpilot/challenge-schema/refs/heads/main/schema.json",
      "enabled": true,
      "name": "A true connection",
      "slug": "a-true-connection",
      "author": "The Mikkel",
      "category": "misc",
      "difficulty": "beginner",
      "tags": [
        "Instanced",
        "TCP",
        "Example"
      ],
      "type": "instanced",
      "instanced_type": "tcp",
      "instanced_name": null,
      "instanced_subdomains": [],
      "connection": null,
      "flag": [
        {
          "flag": "ctfpilot{what-a-connection-you-have-made!}",
          "case_sensitive": false
        }
      ],
      "points": 1000,
      "decay": 75,
      "min_points": 100,
      "description_location": "description.md",
      "handout_dir": "handout",
      "dockerfile_locations": [
        {
          "location": "src/Dockerfile",
          "context": "src/",
          "identifier": null
        }
      ]
    }

  description: |
    # A true connection
    
    **Difficulty:** Beginner  
    **Author:** The Mikkel  
    
    What a connection you can make, if you can connect to the endpoint below!

